server.port=8080

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.routes[0].id=event-service
spring.cloud.gateway.routes[0].uri=lb://event-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/admin/events/**,/events/**,/users/*/events/**,/admin/categories/**,/categories/**,/admin/compilations/**,/compilations/**

spring.cloud.gateway.routes[1].id=request-service
spring.cloud.gateway.routes[1].uri=lb://event-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/users/*/requests/**

spring.cloud.gateway.routes[2].id=user-service
spring.cloud.gateway.routes[2].uri=lb://event-service
spring.cloud.gateway.routes[2].predicates[0]=Path=/admin/users/**

spring.cloud.gateway.routes[3].id=comment-service
spring.cloud.gateway.routes[3].uri=lb://event-service
spring.cloud.gateway.routes[3].predicates[0]=Path=/admin/comments/**,/users/*/comments/**,/users/*/events/*/comments/**,/events/*/comments/**